### ISSUE TITLE
Tracking badly with default settings on my computer

### ISSUE THREAD

**Issue by BluecatLi** [uzh-rpg/direct_event_camera_tracker#1]
Dear Guillermo, I've been following this work and found you kindly released the code last month. I tried to run this branch on my computer. Although I successfully installed the code and ran it, I could not see a good tracking result on my computer, and the output of terminal also shows there is problem in running. My colleague also tried to run it on his computer and met the same problem. Maybe there is some problem in our setting, but I don't know why. Could you please give me some advice?
Here is the description of the problem I met:
1. I installed ROS Melodic on Ubuntu 18.04 by
`sudo apt install ros-melodic-desktop-full`
2. I followed the instructions in Installation chapter and could run 
`rosrun direct_event_camera_tracker direct_event_camera_tracker cfg/main.yaml`
3. I downloaded the dataset and run the node with cfg/main.yaml. I could see the two windows sucessfully.
4. I clicked "load event" to read events from the bagfile. Then clicked "load pose" to load the ground truth pose. Then clicked "generate KF" to generate the first keyframe. Then clicked "track all" to start tracking with the initial setting.
This is before clicking "track all":
![image](https://user-images.githubusercontent.com/78065564/148496932-fd63963f-f102-4b69-870d-f3bcc657bbde.png)
As I did not change anything in the code, I should be able to see a good tracking - Event Frame and Expected intensity change should look similar with optimized pose. However, after about 20 frames of Event Frame, the difference looks too big and tracking is actually bad result.
![image](https://user-images.githubusercontent.com/78065564/148497888-174f9bb5-27ee-466d-acea-eb9c280f681a.png)
Here is the output in terminal:
[Terminal output](https://drive.google.com/file/d/1y81YJ0xC0iTINqJBRXr7RuNHk2da1ukp/view?usp=sharing)
5. I also tried to start tracking without clicking "load pose", but the result is similar. Then I tried to click "track step" several times instead of clicking "track all", the same thing happened.

I checked the version of all the necessary packages but found no difference with your readme file. Please tell me how to acquire a correct tracking. Thank you very much!

**Comment by iliis** [comment]
Thank you for this well written report! I had a look today and it seems that some bugfixes didn't make it into the public release, I'm sorry. I made a [pull request](https://github.com/uzh-rpg/direct_event_camera_tracker/pull/2), can you try it and see if that one works?

**Comment by BluecatLi** [comment]
> Thank you for this well written report! I had a look today and it seems that some bugfixes didn't make it into the public release, I'm sorry. I made a [pull request](https://github.com/uzh-rpg/direct_event_camera_tracker/pull/2), can you try it and see if that one works?

Thank you very much, Bryner. With this new version, I could run it and aquire good tracking result with the provided data.
